"""Rewrite the converter's pipewire.conf.d drop-in into a standalone config for
the plugin's own `pipewire -c` process with fixed node names and target."""
from __future__ import annotations

import re
from typing import Optional, Tuple

from .constants import INPUT_NODE, NODE_BASE, OUTPUT_NODE, SMART_FILTER_NAME

BASE_MODULES = """    { name = libpipewire-module-rt
      args = { }
      flags = [ ifexists nofail ]
    }
    { name = libpipewire-module-protocol-native }
    { name = libpipewire-module-client-node }
    { name = libpipewire-module-adapter }
"""


def strip_comments(text: str) -> str:
    out = []
    for line in text.splitlines():
        if line.lstrip().startswith("#"):
            continue
        out.append(line)
    return "\n".join(out) + "\n"


def extract_module_block(text: str) -> str:
    """Return the single `{ ... }` object inside `context.modules = [ ... ]`."""
    text = strip_comments(text)
    m = re.search(r"context\.modules\s*=\s*\[", text)
    if not m:
        raise ValueError("no context.modules array in converter output")
    start = text.index("{", m.end())
    depth = 0
    in_str = False
    esc = False
    i = start
    while i < len(text):
        c = text[i]
        if in_str:
            if esc:
                esc = False
            elif c == "\\":
                esc = True
            elif c == '"':
                in_str = False
        elif c == '"':
            in_str = True
        elif c == "#":
            nl = text.find("\n", i)
            i = len(text) if nl < 0 else nl
            continue
        elif c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return text[start:i + 1]
        i += 1
    raise ValueError("unbalanced braces in converter output")


def _q(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def rewrite_block(block: str, irs_path: str, description: str, target_sink: str) -> str:
    block = re.sub(r'filename\s*=\s*"[^"]*"', f'filename = "{_q(irs_path)}"', block)
    block = re.sub(r'node\.name\s*=\s*"effect_input\.[^"]*"', f'node.name = "{INPUT_NODE}"', block)
    block = re.sub(r'node\.name\s*=\s*"effect_output\.[^"]*"', f'node.name = "{OUTPUT_NODE}"', block)
    block = re.sub(r'node\.link-group\s*=\s*"[^"]*"', f'node.link-group = "{NODE_BASE}"', block)
    block = re.sub(r'node\.description\s*=\s*"[^"]*"', f'node.description = "{_q(description)}"', block)
    block = re.sub(r'media\.name\s*=\s*"[^"]*"', f'media.name = "{_q(description)}"', block)
    block = re.sub(r'filter\.smart\.name\s*=\s*"[^"]*"', f'filter.smart.name = "{SMART_FILTER_NAME}"', block)
    block, n = re.subn(r'(filter\.smart\.target\s*=\s*\{\s*node\.name\s*=\s*")[^"]*(")',
                       lambda mm: mm.group(1) + _q(target_sink) + mm.group(2), block)
    if n == 0:
        raise ValueError("converter output has no filter.smart.target node.name")
    return block


def compose(block: str, comment: str) -> str:
    comment_lines = "".join(f"# {ln}\n" for ln in comment.splitlines())
    indented = "\n".join(("    " + ln if ln.strip() else ln) for ln in block.splitlines())
    return (
        "# Generated by Ally DSP. Do not edit: regenerated on every preset change.\n"
        + comment_lines
        + "context.properties = {\n    log.level = 2\n}\n"
        + "context.spa-libs = {\n    audio.convert.* = audioconvert/libspa-audioconvert\n"
        + "    support.*       = support/libspa-support\n}\n"
        + "context.modules = [\n" + BASE_MODULES + indented + "\n]\n"
    )


def finalize(conf_text: str, irs_path: str, description: str, target_sink: str, comment: str) -> str:
    block = extract_module_block(conf_text)
    block = rewrite_block(block, irs_path, description, target_sink)
    return compose(block, comment)


_LIMITER_NAME = re.compile(r'name\s*=\s*"(limiter|lim)"')
_GIN = re.compile(r"(\bg_in\s*=\s*)([-+]?[0-9]*\.?[0-9]+(?:[eE][-+]?[0-9]+)?)")


def limiter_input_gain(conf_text: str) -> Optional[float]:
    m = _LIMITER_NAME.search(conf_text)
    if not m:
        return None
    mm = _GIN.search(conf_text, m.end())
    return float(mm.group(2)) if mm else None


def set_pregain_db(conf_text: str, db: float, base_gain: Optional[float] = None) -> Tuple[str, bool]:
    """Scale the limiter input gain by `db` relative to `base_gain` (the converter's value)."""
    m = _LIMITER_NAME.search(conf_text)
    if not m:
        return conf_text, False
    mm = _GIN.search(conf_text, m.end())
    if not mm:
        return conf_text, False
    base = base_gain if base_gain is not None else float(mm.group(2))
    new = base * (10.0 ** (db / 20.0))
    return conf_text[:mm.start(2)] + f"{new:.9g}" + conf_text[mm.end(2):], True
