export const t = {
  title: "Ally DSP",
  status: "Status",
  active: "active",
  inactive: "inactive",
  pausedHeadphones: "paused (headphones)",
  notSetUp: "Not set up yet",
  setupNeeded: "The Dolby tuning has to be downloaded and converted once.",
  runSetup: "Run setup",
  rerunSetup: "Run setup again",
  sound: "Sound",
  dspEnabled: "DSP enabled",
  dspEnabledDesc: "Off = bypass for A/B comparison",
  preset: "Preset (global)",
  voicing: "Voicing",
  thisGame: "This game",
  perGameToggle: "Use a dedicated preset for this game",
  perGamePreset: "Preset",
  noGame: "No game is running. Per-game presets appear here while a game runs.",
  savedPerGame: "Saved per-game presets",
  remove: "Remove",
  extras: "Extras",
  autogain: "Volume leveler",
  autogainDesc: "Dolby loudness leveling (default on). Turn off if you hear pumping.",
  dialog: "Dialog enhancer",
  regulator: "Regulator",
  regulatorDesc: "Dolby's overdrive protection. Only disable if the volume wobbles.",
  virtualBass: "Virtual bass (experimental)",
  preGain: "Pre-gain",
  reconverting: "Regenerating presets…",
  maintenance: "Maintenance",
  checkUpdate: "Check for updates",
  updateAvailable: "Update available",
  installUpdate: "Install update",
  upToDate: "Up to date",
  updateFailed: "Update failed",
  diagnostics: "Diagnostics",
  setupTitle: "Set up Ally DSP",
  setupIntro: "Downloads ASUS' Dolby package (about 10 MB) onto this device, extracts the tuning for its codec and converts it into PipeWire presets. A Python environment with numpy/scipy (about 220 MB) is created once. Nothing leaves the device.",
  start: "Start",
  cancel: "Cancel",
  back: "Back",
  refresh: "Refresh",
  done: "Done",
  stepHardware: "Check hardware",
  stepResolve: "Locate ASUS package",
  stepDownload: "Download",
  stepExtract: "Extract tuning",
  stepVenv: "Prepare converter",
  stepConvert: "Convert presets",
  stepActivate: "Activate",
  unsupported: "This device is not supported",
  forceUnsupported: "Try anyway",
  version: "Version",
  staleUi: "Interface is from an older version. Restart Steam to load the updated UI.",
};

export const STEP_LABELS: Record<string, string> = {
  hardware: t.stepHardware,
  resolve: t.stepResolve,
  download: t.stepDownload,
  extract: t.stepExtract,
  venv: t.stepVenv,
  convert: t.stepConvert,
  activate: t.stepActivate,
};
