const de = {
  title: "Ally DSP",
  status: "Status",
  active: "aktiv",
  inactive: "inaktiv",
  pausedHeadphones: "pausiert (Kopfhörer)",
  notSetUp: "Noch nicht eingerichtet",
  setupNeeded: "Das Dolby-Tuning muss einmalig heruntergeladen und umgewandelt werden.",
  runSetup: "Setup starten",
  rerunSetup: "Setup erneut ausführen",
  sound: "Klang",
  dspEnabled: "DSP aktiv",
  dspEnabledDesc: "Aus = Bypass zum A/B-Vergleich",
  preset: "Preset (global)",
  voicing: "Voicing",
  thisGame: "Dieses Spiel",
  perGameToggle: "Eigenes Preset für dieses Spiel",
  perGamePreset: "Preset",
  noGame: "Kein Spiel läuft. Per-Game-Presets erscheinen hier, sobald ein Spiel gestartet ist.",
  savedPerGame: "Gespeicherte Spiel-Presets",
  remove: "Entfernen",
  extras: "Extras",
  autogain: "Volume Leveler",
  autogainDesc: "Dolby-Lautheitsausgleich (Standard an). Bei hörbarem Pumpen ausschalten.",
  dialog: "Dialog-Enhancer",
  regulator: "Regulator",
  regulatorDesc: "Dolbys Übersteuerungsschutz. Nur ausschalten, wenn die Lautstärke wogt.",
  virtualBass: "Virtual Bass (experimentell)",
  preGain: "Pre-Gain",
  reconverting: "Presets werden neu erzeugt …",
  maintenance: "Wartung",
  checkUpdate: "Nach Updates suchen",
  updateAvailable: "Update verfügbar",
  installUpdate: "Update installieren",
  upToDate: "Aktuell",
  updateFailed: "Update fehlgeschlagen",
  diagnostics: "Diagnose",
  setupTitle: "Ally DSP einrichten",
  setupIntro: "Lädt ASUS' Dolby-Paket (≈10 MB) auf dieses Gerät, extrahiert das Tuning für den Codec und wandelt es in PipeWire-Presets um. Dafür wird einmalig eine Python-Umgebung mit numpy/scipy (≈220 MB) angelegt. Nichts davon verlässt das Gerät.",
  start: "Start",
  cancel: "Abbrechen",
  back: "Zurück",
  refresh: "Aktualisieren",
  done: "Fertig",
  stepHardware: "Hardware prüfen",
  stepResolve: "ASUS-Paket ermitteln",
  stepDownload: "Herunterladen",
  stepExtract: "Tuning extrahieren",
  stepVenv: "Konverter vorbereiten",
  stepConvert: "Presets umwandeln",
  stepActivate: "Aktivieren",
  unsupported: "Dieses Gerät wird nicht unterstützt",
  forceUnsupported: "Trotzdem versuchen",
  version: "Version",
};

const en: typeof de = {
  title: "Ally DSP",
  status: "Status",
  active: "active",
  inactive: "inactive",
  pausedHeadphones: "paused (headphones)",
  notSetUp: "Not set up yet",
  setupNeeded: "The Dolby tuning has to be downloaded and converted once.",
  runSetup: "Run setup",
  rerunSetup: "Run setup again",
  sound: "Sound",
  dspEnabled: "DSP enabled",
  dspEnabledDesc: "Off = bypass for A/B comparison",
  preset: "Preset (global)",
  voicing: "Voicing",
  thisGame: "This game",
  perGameToggle: "Use a dedicated preset for this game",
  perGamePreset: "Preset",
  noGame: "No game is running. Per-game presets appear here while a game runs.",
  savedPerGame: "Saved per-game presets",
  remove: "Remove",
  extras: "Extras",
  autogain: "Volume leveler",
  autogainDesc: "Dolby loudness leveling (default on). Turn off if you hear pumping.",
  dialog: "Dialog enhancer",
  regulator: "Regulator",
  regulatorDesc: "Dolby's overdrive protection. Only disable if the volume wobbles.",
  virtualBass: "Virtual bass (experimental)",
  preGain: "Pre-gain",
  reconverting: "Regenerating presets…",
  maintenance: "Maintenance",
  checkUpdate: "Check for updates",
  updateAvailable: "Update available",
  installUpdate: "Install update",
  upToDate: "Up to date",
  updateFailed: "Update failed",
  diagnostics: "Diagnostics",
  setupTitle: "Set up Ally DSP",
  setupIntro: "Downloads ASUS' Dolby package (≈10 MB) onto this device, extracts the tuning for its codec and converts it into PipeWire presets. A Python environment with numpy/scipy (≈220 MB) is created once. Nothing leaves the device.",
  start: "Start",
  cancel: "Cancel",
  back: "Back",
  refresh: "Refresh",
  done: "Done",
  stepHardware: "Check hardware",
  stepResolve: "Locate ASUS package",
  stepDownload: "Download",
  stepExtract: "Extract tuning",
  stepVenv: "Prepare converter",
  stepConvert: "Convert presets",
  stepActivate: "Activate",
  unsupported: "This device is not supported",
  forceUnsupported: "Try anyway",
  version: "Version",
};

function pickLanguage(): typeof de {
  try {
    const lang = (navigator.language || "en").toLowerCase();
    return lang.startsWith("de") ? de : en;
  } catch {
    return en;
  }
}

export const t = pickLanguage();

export const STEP_LABELS: Record<string, string> = {
  hardware: t.stepHardware,
  resolve: t.stepResolve,
  download: t.stepDownload,
  extract: t.stepExtract,
  venv: t.stepVenv,
  convert: t.stepConvert,
  activate: t.stepActivate,
};
